name: CMake on multiple platforms

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                compiler: [gcc, clang, cl]
                build_type: [Release, Debug]
                include:
                    - os: windows-latest
                      compiler: cl
                      c_compiler: cl
                      cpp_compiler: cl
                    - os: ubuntu-latest
                      compiler: gcc
                      c_compiler: gcc
                      cpp_compiler: g++
                    - os: ubuntu-latest
                      compiler: clang
                      c_compiler: clang
                      cpp_compiler: clang++
                    - os: macos-latest
                      compiler: clang
                      c_compiler: clang
                      cpp_compiler: clang++

        steps:
            - uses: actions/checkout@v4

            - name: Debug Matrix Values
              run: env

            - name: Set Default Compilers
              run: |
                  if [ -z "${{ matrix.c_compiler }}" ]; then
                    echo "Using default C compiler: gcc"
                    export CC=gcc
                  else
                    export CC=${{ matrix.c_compiler }}
                  fi
                  
                  if [ -z "${{ matrix.cpp_compiler }}" ]; then
                    echo "Using default C++ compiler: g++"
                    export CXX=g++
                  else
                    export CXX=${{ matrix.cpp_compiler }}
                  fi
                  
                  echo "C Compiler: $CC"
                  echo "C++ Compiler: $CXX"

            - name: Set Build Directory
              run: echo "build-output-dir=${{ github.workspace }}/build" >> $GITHUB_ENV

            - name: Create Build Directory
              run: mkdir -p ${{ env.build-output-dir }}

            - name: Configure CMake
              run: >
                  cmake -B ${{ env.build-output-dir }}
                  -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
                  -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
                  -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
                  -DCMAKE_PREFIX_PATH=/opt/homebrew;/usr/local/vcpkg/installed/x64-windows
                  -S ${{ github.workspace }}

            - name: Build
              run: cmake --build ${{ env.build-output-dir }} --config ${{ matrix.build_type }}

            - name: Test
              working-directory: ${{ env.build-output-dir }}
              run: ctest --build-config ${{ matrix.build_type }}